### ISSUE TITLE
`all` config

### ISSUE THREAD

**Issue by DetachHead** [ota-meshi/eslint-plugin-svelte#406] opened 2023-03-17 07:09 UTC
### Description

i would like to have all rules enabled by default, so i can explicitly disable the ones i don't want. this would make it easier to discover new rules when i update my version of eslint-plugin-svelte

**Comment by DetachHead** [comment] 2023-03-17 07:12
since it would be annoying to have to maintain another list of all rules, you could generate it dynamically like i did with my eslint plugin: https://github.com/DetachHead/eslint-plugin-detachhead/blob/15a09f881fc6518b66b9da1bcbdccdfc67ef99d0/src/index.ts

**Comment by ota-meshi** [comment] 2023-03-17 07:17
Duplicate of #369.
I welcome PR!

**Closed by ota-meshi** 2023-03-17 07:17 UTC
Labels: enhancement
